### PR TITLE
892: changes names of status filter options to fix project stage filter

### PR DESCRIPTION
**Pull request by trbmcginnis**

### CODE REVIEW

**Review by allthesignals — APPROVED** [review]
Woops! Good catch. Thank you so much.

**Comment by andycochran** [comment]
🤔 I don't understand how we can build a query for `dcp_publicstatus` using UI values we're creating for `dcp_publicstatus_simp`.

**Comment by allthesignals** [comment]
@andycochran hmm yeah let's look into that

**Comment by allthesignals** [comment]
@trbmcginnis what issue does this fix?

**Pull request merged**
